# Generated by Django 4.2.6 on 2023-11-02 22:25

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_file',
            field=models.FileField(upload_to=api.models.video_upload_to),
        ),
        migrations.CreateModel(
            name='Subclips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclip_file', models.FileField(upload_to='subvid/')),
                ('duration', models.FloatField()),
                ('parent_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclips', to='api.parentfolder')),
            ],
        ),
    ]
