# Generated by Django 4.2.6 on 2023-11-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parentfolder_alter_videos_video_file_subclips'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='crvid/')),
                ('target_resolution_x', models.IntegerField()),
                ('target_resolution_y', models.IntegerField()),
                ('original_resolution_x', models.IntegerField()),
                ('original_resolution_y', models.IntegerField()),
            ],
        ),
    ]
