# Generated by Django 4.2.6 on 2023-11-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_crvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcatVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.FileField(upload_to='concatvid/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CRvideo',
        ),
    ]
